name: CI/CD for building, packaging and updating the DolphinOS repo

on: workflow_dispatch

jobs:
  build_packages:
    name: Create and build Arch packages
    runs-on: ubuntu-latest

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
    - uses: actions/checkout@v2
    - name: Update packages and install required dependencies for the job
      run: |
        pacman -Syu --noconfirm --needed sudo git base-devel
        useradd builduser -m
        passwd -d builduser
        echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        mkdir buildworkdir
        chown -R builduser buildworkdir
        cd buildworkdir
        sudo -u builduser git clone https://aur.archlinux.org/yay-bin.git
        cd yay-bin
        sudo -u builduser makepkg -si --noconfirm
    - name: Clone PKGBUILDs repository
      run: |
        cd buildworkdir
        sudo -u builduser git clone https://github.com/DolphinOS-Development/DolphinOS-PKGBUILDs.git
    - name: Build packages
      run: |
        mkdir -p x86_64
        cd buildworkdir/DolphinOS-PKGBUILDs
        dirs=($(find * -maxdepth 0 -type d))
        for dir in "${dirs[@]}"
        do
          cd "$(pwd)/$dir"
          sudo -u builduser makepkg -s --noconfirm
          cp -v *.pkg.tar.zst $GITHUB_WORKSPACE/x86_64
          cd ..
        done
    - name: Clean buildworkdir
      run: |
        rm -rf buildworkdir
    - name: Commit changes and push packages to repo
      run: |
        git config --global user.name 'JesusXD88'
        git config --global user.email 'JesusXD88@users.noreply.github.com'
        git commit -am "Updated packages"
        git push