name: CI/CD for building, packaging and updating the DolphinOS repo

on: workflow_dispatch

jobs:
  build_packages:
    name: Create and build Arch packages
    runs-on: ubuntu-latest

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
    - uses: actions/checkout@v2
    - name: Update packages and install required dependencies for the job
      run: |
        pacman -Syu --noconfirm --needed sudo git base-devel
        useradd builduser -m
        passwd -d builduser
        echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        sudo -u builduser mkdir buildworkdir
        sudo -u builduser chmod -R a+rw buildworkdir
        cd buildworkdir
        whoami
        echo -e "\n"
        ls -lah
        echo -e "\n"
        ls -lah ..
        git clone https://aur.archlinux.org/yay-bin.git
        cd yay-bin
        sudo -u builduser makepkg -si
    - name: Clone PKGBUILDs repository
      run: |
        git clone https://github.com/DolphinOS-Development/DolphinOS-PKGBUILDs.git